### ISSUE TITLE
watch_psutil.py script error

### ISSUE THREAD

**Issue by kirklatslalom** [ChristianKniep/docker-terminal#8]
The watch_psutil.py script seems to have a typo

elk_1      | 2015-08-05 23:16:17,270 INFO exited: watchpsutil (exit status 1; not expected)
elk_1      | 2015-08-05 23:16:17,575 INFO spawned: 'watchpsutil' with pid 478
elk_1      | 2015-08-05 23:16:18,687 INFO success: watchpsutil entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
elk_1      | 2015-08-05 23:16:22,659 INFO exited: watchpsutil (exit status 1; not expected)
elk_1      | 2015-08-05 23:16:22,711 INFO spawned: 'watchpsutil' with pid 533
elk_1      | 2015-08-05 23:16:23,715 INFO success: watchpsutil entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Running python -m trace --count -C . watch_psutil.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/trace.py", line 819, in <module>
    main()
  File "/usr/lib64/python2.7/trace.py", line 807, in main
    t.runctx(code, globs, globs)
  File "/usr/lib64/python2.7/trace.py", line 513, in runctx
    exec cmd in globals, locals
  File "watch_psutil.py", line 300, in <module>
    main()
  File "watch_psutil.py", line 291, in main
    proc = WatchPs(qcfg)
  File "watch_psutil.py", line 212, in __init__
    self.cnt_gsend()
  File "watch_psutil.py", line 230, in cnt_gsend
    self.con_gsend()
AttributeError: 'WatchPs' object has no attribute 'con_gsend'

It looks like 'con_gsend' should be cnt_gsend

diff --git a/opt/qnib/bin/watch_psutil.py b/opt/qnib/bin/watch_psutil.py
index f1ef41d..4fbddff 100755
--- a/opt/qnib/bin/watch_psutil.py
+++ b/opt/qnib/bin/watch_psutil.py
@@ -227,7 +227,7 @@ class WatchPs(object):
             self._gsend = graphitesend.init(graphite_server=self._cfg['--carbon-host'], prefix=pre)
         except graphitesend.GraphiteSendException:
             time.sleep(5)
-            self.con_gsend()
+            self.cnt_gsend()

     def run(self):
         """ run the function

**Comment by ChristianKniep** [comment]
Ohh... that easy? It must be more complex... :) :+1:
